In [ ]:
import numpy as np

def softmax(x):
    exp_x = np.exp(x - np.max(x))
    return exp_x / np.sum(exp_x)

In [ ]:
Q = np.random.rand(3, 4)
K = np.random.rand(3, 4)
V = np.random.rand(3, 4)

print(Q)
print(K)
print(V)

[[0.93205442 0.00545696 0.77837369 0.97642069]
 [0.52341954 0.1216824  0.66105743 0.63252221]
 [0.66606599 0.4025959  0.56965994 0.39127708]]
[[0.75835063 0.38434143 0.38235323 0.25769954]
 [0.01358507 0.84081337 0.31565992 0.72461295]
 [0.95503947 0.61571133 0.60877146 0.99357035]]
[[0.82994491 0.18099438 0.87921534 0.24569946]
 [0.23764788 0.62277926 0.12463789 0.54394431]
 [0.16817316 0.56435919 0.76970097 0.05412966]]


In [ ]:
scores = np.dot(Q, K.T)
print(scores)

[[1.25815825 0.97047877 2.337503  ]
 [0.85946125 0.77642601 1.60569576]
 [0.97848909 0.81089982 1.61955618]]


In [ ]:
attention_weights = softmax(scores)
print(attention_weights)

[[0.09777098 0.07332843 0.28771563]
 [0.0656233  0.06039435 0.1384024 ]
 [0.07391817 0.06251268 0.14033407]]


In [ ]:
output = np.dot(attention_weights, V)
print(output)

[[0.14695692 0.22573838 0.31655624 0.07948281]
 [0.09209188 0.12759846 0.1717529  0.05646645]
 [0.09980444 0.13150919 0.1807967  0.05976131]]
